//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Projects/P02-ObjectPool/P02_Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @P02_Input : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @P02_Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""P02_Input"",
    ""maps"": [
        {
            ""name"": ""General"",
            ""id"": ""60d3597a-829c-41cb-81aa-9b46b5b5673b"",
            ""actions"": [
                {
                    ""name"": ""Release"",
                    ""type"": ""Button"",
                    ""id"": ""1b7e18dc-2ed7-4f48-90ee-24f25995e2f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Activate"",
                    ""type"": ""Button"",
                    ""id"": ""b7e04eea-fa18-4e57-b4a0-2a848b83bc19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""eb95edd1-861f-43fb-957d-86324f624117"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""096d44f0-6a22-4dca-95aa-1c620bf4812b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Activate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_Release = m_General.FindAction("Release", throwIfNotFound: true);
        m_General_Activate = m_General.FindAction("Activate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General
    private readonly InputActionMap m_General;
    private IGeneralActions m_GeneralActionsCallbackInterface;
    private readonly InputAction m_General_Release;
    private readonly InputAction m_General_Activate;
    public struct GeneralActions
    {
        private @P02_Input m_Wrapper;
        public GeneralActions(@P02_Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @Release => m_Wrapper.m_General_Release;
        public InputAction @Activate => m_Wrapper.m_General_Activate;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void SetCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterface != null)
            {
                @Release.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnRelease;
                @Release.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnRelease;
                @Release.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnRelease;
                @Activate.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnActivate;
                @Activate.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnActivate;
                @Activate.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnActivate;
            }
            m_Wrapper.m_GeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Release.started += instance.OnRelease;
                @Release.performed += instance.OnRelease;
                @Release.canceled += instance.OnRelease;
                @Activate.started += instance.OnActivate;
                @Activate.performed += instance.OnActivate;
                @Activate.canceled += instance.OnActivate;
            }
        }
    }
    public GeneralActions @General => new GeneralActions(this);
    public interface IGeneralActions
    {
        void OnRelease(InputAction.CallbackContext context);
        void OnActivate(InputAction.CallbackContext context);
    }
}
